// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';

// Load environment variables based on NODE_ENV (same as NestJS config)
const nodeEnv = process.env.NODE_ENV ?? 'development';
const envFilePath = [`.env.${nodeEnv}`, '.env'];
for (const path of envFilePath) {
  config({ path });
}

const { DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME } = process.env;

let databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  if (!DB_HOST || !DB_PORT || !DB_USER || !DB_PASSWORD || !DB_NAME) {
    throw new Error(
      'Database connection details are not fully provided. Please check your .env file for DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, and DB_NAME, or provide a DATABASE_URL.',
    );
  }
  databaseUrl = `mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}`;
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'ts-node prisma/seed.ts',
  },
  datasource: {
    url: databaseUrl,
  },
});
