// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Load environment variables based on NODE_ENV (same as NestJS config)
const nodeEnv = process.env.NODE_ENV ?? "development";
const envFilePath = [`.env.${nodeEnv}`, ".env"];
for (const path of envFilePath) {
  config({ path });
}

const databaseUrl = process.env.DATABASE_URL; 

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
